# Numpy


In [1]:
import numpy as np

In [3]:
print(len(dir(np)))

622


###### Array Creation Printing Arrays, Basic Operations- Indexing, Slicing and Iterating

In [4]:
a = np.array([])
a

array([], dtype=float64)

In [5]:
a = np.array(())
a

array([], dtype=float64)

In [10]:
a = np.array([1,2,3,4])
print(a)
a

[1 2 3 4]


array([1, 2, 3, 4])

In [7]:
a = np.array((1,2,3,4))
a

array([1, 2, 3, 4])

In [11]:
a = np.array([1,2])
a

array([1, 2])

In [8]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a = np.array([[1,2,3],[4,5,6],[7,8,9,10]])
a

array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9, 10])],
      dtype=object)

In [13]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
print(a.dtype)
print(a.shape) # Number of rows and columns
print(a.ndim) # Number of dimensions
print(a.itemsize) # Number of bytes consumed by one element of an array
print(a.size) # Number of elements in array
print(len(a))

int32
(3, 3)
2
4
9
3


In [20]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [21]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [22]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Controlling data type

In [24]:
a = np.array([[1,2,3],[4,5,6],[7,8.2,9]])
a.dtype

dtype('float64')

In [25]:
a = np.array([[1,2,3],[4,5,6],[7,8.2,'a']])
a.dtype

dtype('<U32')

In [30]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.dtype

dtype('int32')

In [28]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='int16')
a.dtype

dtype('int16')

In [29]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.int8)
a.dtype

dtype('int8')

In [29]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.int8)
a.dtype

dtype('int8')

#### Shape Manipulation - Changing shape,

In [39]:
a = np.random.randint(1,20,20)
b = a.reshape(5,4)
b

array([[ 9, 15,  3, 15],
       [16, 18,  6,  7],
       [18,  9, 11, 16],
       [ 1, 18, 13,  6],
       [ 3, 17, 15, 19]])

## Indexing and slicing of an array

In [42]:
print(b)

[[ 9 15  3 15]
 [16 18  6  7]
 [18  9 11 16]
 [ 1 18 13  6]
 [ 3 17 15 19]]


In [43]:
b[2][1]

9

In [ ]:
# Syntax:
# <array>[<row>,<col>]

In [44]:
b

array([[ 9, 15,  3, 15],
       [16, 18,  6,  7],
       [18,  9, 11, 16],
       [ 1, 18, 13,  6],
       [ 3, 17, 15, 19]])

In [45]:
b[::,::]

array([[ 9, 15,  3, 15],
       [16, 18,  6,  7],
       [18,  9, 11, 16],
       [ 1, 18, 13,  6],
       [ 3, 17, 15, 19]])

In [46]:
b[:,:]

array([[ 9, 15,  3, 15],
       [16, 18,  6,  7],
       [18,  9, 11, 16],
       [ 1, 18, 13,  6],
       [ 3, 17, 15, 19]])

In [47]:
b[::-1,::-1]

array([[19, 15, 17,  3],
       [ 6, 13, 18,  1],
       [16, 11,  9, 18],
       [ 7,  6, 18, 16],
       [15,  3, 15,  9]])

In [ ]:
# [Start:End:stepSize]

In [49]:
b 

array([[ 9, 15,  3, 15],
       [16, 18,  6,  7],
       [18,  9, 11, 16],
       [ 1, 18, 13,  6],
       [ 3, 17, 15, 19]])

In [51]:
b[2:4,1:]

array([[ 9, 11, 16],
       [18, 13,  6]])

In [52]:
b[2,1:]

array([ 9, 11, 16])

In [53]:
b

array([[ 9, 15,  3, 15],
       [16, 18,  6,  7],
       [18,  9, 11, 16],
       [ 1, 18, 13,  6],
       [ 3, 17, 15, 19]])

In [54]:
b[1:4,1:3]

array([[18,  6],
       [ 9, 11],
       [18, 13]])

###### stacking arrays

In [70]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
# b = np.array([[5,6],[7,8],[9,10]])

In [71]:
a

array([[1, 2],
       [3, 4]])

In [72]:
b

array([[5, 6],
       [7, 8]])

In [73]:
np.vstack([a,b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [74]:
np.hstack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

###### Transpose of an array

In [75]:
a = np.array([[1,2],[3,4],[5,6],[7,8]])
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [76]:
a.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [77]:
np.transpose(a)

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

###### Creating zeros,ones and identity matrix

###### zeros

In [79]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###### ones

In [80]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

###### identity

In [84]:
np.identity(4,dtype='int8')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

#### Create 8x8 matrix and replace all the element to zero which is above diagonal. repeat again and do it for lower diagonal values

In [92]:
a = np.random.randint(1,30,64).reshape(8,8)
a

array([[24, 12, 14, 24,  3,  3, 19,  9],
       [ 2,  8, 15, 22, 14, 10, 11, 26],
       [ 5, 28, 18, 21, 25, 21, 22, 11],
       [19,  1, 21, 16,  9,  9, 24, 12],
       [ 5, 29,  8, 11,  9, 24, 12, 25],
       [10, 29,  6, 11, 29, 22,  1,  5],
       [ 9, 23, 22, 26,  2,  7,  9, 11],
       [ 8, 17,  4,  8, 15, 11, 21,  5]])

In [93]:
cnt = 0
for row in a:
    row[cnt+1:] = 0
    cnt +=1
a

array([[24,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  8,  0,  0,  0,  0,  0,  0],
       [ 5, 28, 18,  0,  0,  0,  0,  0],
       [19,  1, 21, 16,  0,  0,  0,  0],
       [ 5, 29,  8, 11,  9,  0,  0,  0],
       [10, 29,  6, 11, 29, 22,  0,  0],
       [ 9, 23, 22, 26,  2,  7,  9,  0],
       [ 8, 17,  4,  8, 15, 11, 21,  5]])

In [94]:
a = np.random.randint(1,30,64).reshape(8,8)
a

array([[25,  5,  1, 10, 24, 27, 12, 13],
       [25, 14,  6, 14, 19,  3,  9, 19],
       [22, 11, 25, 19,  9, 27, 10, 13],
       [ 4, 16, 16,  6, 28, 21,  9,  4],
       [ 4, 12,  2,  7,  3, 22, 25, 15],
       [26,  7,  1, 29, 25, 29, 16, 15],
       [16,  3, 15,  9, 10,  6, 10, 17],
       [11, 10, 28, 11, 11, 14, 14, 18]])

In [95]:
cnt = 0
for row in a:
    row[:cnt] = 0
    cnt +=1
a

array([[25,  5,  1, 10, 24, 27, 12, 13],
       [ 0, 14,  6, 14, 19,  3,  9, 19],
       [ 0,  0, 25, 19,  9, 27, 10, 13],
       [ 0,  0,  0,  6, 28, 21,  9,  4],
       [ 0,  0,  0,  0,  3, 22, 25, 15],
       [ 0,  0,  0,  0,  0, 29, 16, 15],
       [ 0,  0,  0,  0,  0,  0, 10, 17],
       [ 0,  0,  0,  0,  0,  0,  0, 18]])

###### Arithmetic operation, Matrix multiplication

In [96]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [97]:
print(a*2)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [98]:
print(a**2)

[[ 1  4]
 [ 9 16]
 [25 36]]


In [101]:
a = np.array([[1,2],[3,4]])
b = np.array([[0,1],[7,8]])
print(a)
print('$'*5)
print(b)

[[1 2]
 [3 4]]
$$$$$
[[0 1]
 [7 8]]


In [102]:
a*b

array([[ 0,  2],
       [21, 32]])

In [103]:
a+b

array([[ 1,  3],
       [10, 12]])

## matrix multiplication

In [104]:
np.dot(a,b)

array([[14, 17],
       [28, 35]])

###### Filtering values from an array w/ and w/o where function

In [105]:
a = np.random.randint(1,20,30).reshape(6,5)
a

array([[10,  9, 13, 17, 14],
       [ 4,  2, 15, 19, 12],
       [ 2,  3, 14, 11,  2],
       [16, 18, 14,  2,  1],
       [15, 13,  9, 17,  7],
       [11, 14,  1,  6, 19]])

In [ ]:
# Syntax:
# np.where((<condition1>) & (<condition2>)....)

In [108]:
idx = np.where(a<10)
idx

(array([0, 1, 1, 2, 2, 2, 3, 3, 4, 4, 5, 5], dtype=int64),
 array([1, 0, 1, 0, 1, 4, 3, 4, 2, 4, 2, 3], dtype=int64))

In [109]:
a[idx]

array([9, 4, 2, 2, 3, 2, 2, 1, 9, 7, 1, 6])

In [110]:
a[a<10]

array([9, 4, 2, 2, 3, 2, 2, 1, 9, 7, 1, 6])

In [112]:
a[(a<15) & (a>10)]

array([13, 14, 12, 14, 11, 14, 13, 11, 14])

In [113]:
a[(a<15) & (a>10)].size

9

In [114]:
len(a[(a<15) & (a>10)])

9

###### Applying statistic function over array (to whole elements or row wise or column wise)

In [117]:
a = np.random.randint(1,10,15).reshape(5,3)
a

array([[9, 4, 5],
       [3, 1, 9],
       [1, 3, 8],
       [1, 2, 6],
       [6, 3, 5]])

In [118]:
print(a.min())

1


In [119]:
print(a.max())

9


In [123]:
# axis = 0 : for column wise
# axis = 1 : for row wise

In [120]:
print(a.min(axis=0))

[1 1 5]


In [121]:
print(a.std(axis=0))

[3.09838668 1.0198039  1.62480768]


In [122]:
print(a.std(axis=1))

[2.1602469  3.39934634 2.94392029 2.1602469  1.24721913]


In [124]:
a

array([[9, 4, 5],
       [3, 1, 9],
       [1, 3, 8],
       [1, 2, 6],
       [6, 3, 5]])

In [125]:
a[:,0].std()

3.0983866769659336

In [126]:
a[0,:].std()

2.160246899469287

In [127]:
print(a.mean(axis=1))

[6.         4.33333333 4.         3.         4.66666667]


In [128]:
print(a.median(axis=1))

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [129]:
print(a.var(axis=1))

[ 4.66666667 11.55555556  8.66666667  4.66666667  1.55555556]
